server:
  port: 8087
  servlet:
    context-path: /api/service-acquisition

logging:
  level:
    root: info
    org:
      flywaydb: debug

springdoc:
  enable-native-support: true
  swagger-ui.path: /swagger-ui

spring:
  profiles:
    active: local
  application:
    name: service-acquisition
  datasource:
    url: jdbc:mariadb://localhost:3306/service-acquisition
    username: root
    password: root
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mariadb://localhost:3306
    user: root
    password: root
    schemas: service-acquisition
iam:
  user:
    account-url: ${account-url:https://qa-user-account-service.coderfull.com}
---
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    url: ${conection_string}
    username: ${username}
    password: ${password}
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: ${conection_string}
    user: ${username}
    password: ${password}
    schemas: service-acquisition-qa

iam:
  user:
    account-url: ${account-url:https://qa-user-account-service.coderfull.com}
---
spring:
  config:
    activate:
      on-profile: stage
  datasource:
    url: ${conection_string}
    username: ${username}
    password: ${password}
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: ${conection_string}
    user: ${username}
    password: ${password}
    schemas: service-acquisition-stage
iam:
  user:
    account-url: ${account-url:https://stage-user-account-service.coderfull.com}
---
spring:
  config:
    activate:
      on-profile: uat
  datasource:
    url: ${conection_string}
    username: ${username}
    password: ${password}
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: ${conection_string}
    user: ${username}
    password: ${password}
    schemas: service-acquisition-prod
iam:
  user:
    account-url: ${account-url:https://uat-user-account-service.coderfull.com}
---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: ${conection_string}
    username: ${username}
    password: ${password}
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: ${conection_string}
    user: ${username}
    password: ${password}
    schemas: service-acquisition-prod

iam:
  user:
    account-url: ${account-url:https://user-account-service.coderfull.com}