server:
  port: 8087
  servlet:
    context-path: /

logging:
  level:
    root: info
    org:
      flywaydb: debug

spring:
  profiles:
    active: local
  application:
    name: service-acquisition
  datasource:
    url: jdbc:mariadb://localhost:3306/service-acquisition
    username: root
    password: root
    driverClassName: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false
    baseline-on-migrate: false
    url: jdbc:mariadb://localhost:3306
    user: root
    password: root
    schemas: service-management