server:
  port: 8087
  servlet:
    context-path: /api/service-acquisition

logging:
  level:
    root: info
    org:
      flywaydb: debug

springdoc:
  enable-native-support: true
  swagger-ui.path: /swagger-ui

spring:
  profiles:
    active: local
  application:
    name: service-acquisition
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:teamfinder;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;MODE=MySQL
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false
    baseline-on-migrate: false
    url: jdbc:mariadb://localhost:3306
    user: root
    password: root
    schemas: service-management