INSERT INTO technology(id, description)VALUES(6, '.NET');
INSERT INTO technology(id, description)VALUES(7, 'Android');
INSERT INTO technology(id, description)VALUES(8, 'Angular');
INSERT INTO technology(id, description)VALUES(9, 'Appium');
INSERT INTO technology(id, description)VALUES(10, 'AWS');
INSERT INTO technology(id, description)VALUES(11, 'C/C++');
INSERT INTO technology(id, description)VALUES(12, 'iOS');
INSERT INTO technology(id, description)VALUES(13, 'Java');
INSERT INTO technology(id, description)VALUES(14, 'Javascript');
INSERT INTO technology(id, description)VALUES(15, 'N/A');
INSERT INTO technology(id, description)VALUES(16, 'NodeJs');
INSERT INTO technology(id, description)VALUES(17, 'PHP');
INSERT INTO technology(id, description)VALUES(18, 'Python');
INSERT INTO technology(id, description)VALUES(19, 'React');
INSERT INTO technology(id, description)VALUES(20, 'Ruby');
INSERT INTO technology(id, description)VALUES(21, 'Swift');
INSERT INTO technology(id, description)VALUES(22, 'Xamarin');
INSERT INTO technology(id, description)VALUES(36, 'Terraform');
INSERT INTO technology(id, description)VALUES(37, 'Ansible');
INSERT INTO technology(id, description)VALUES(38, 'Chef');
INSERT INTO technology(id, description)VALUES(39, 'Docker');
INSERT INTO technology(id, description)VALUES(40, 'Kubernetes');
INSERT INTO technology(id, description)VALUES(41, 'Selenium');
INSERT INTO technology(id, description)VALUES(42, 'C#');
INSERT INTO technology(id, description)VALUES(43, 'Scrum');
INSERT INTO technology(id, description)VALUES(44, 'Agile');
INSERT INTO technology(id, description)VALUES(45, 'Go');
INSERT INTO technology(id, description)VALUES(46, 'Scala');
INSERT INTO technology(id, description)VALUES(47, 'React Native');
INSERT INTO technology(id, description)VALUES(48, 'Cordova');
INSERT INTO technology(id, description)VALUES(49, 'Vagrant');
INSERT INTO technology(id, description)VALUES(50, 'Linux');
INSERT INTO technology(id, description)VALUES(51, 'Azure');
INSERT INTO technology(id, description)VALUES(52, 'Kanban');
INSERT INTO technology(id, description)VALUES(53, 'Jira');
INSERT INTO technology(id, description)VALUES(54, 'Confluence');
INSERT INTO technology(id, description)VALUES(55, 'Lucidchart');
INSERT INTO technology(id, description)VALUES(56, 'Acceptance T.');
INSERT INTO technology(id, description)VALUES(57, 'Smoke T.');
INSERT INTO technology(id, description)VALUES(58, 'Usability T.');
INSERT INTO technology(id, description)VALUES(59, 'Integration T.');
INSERT INTO technology(id, description)VALUES(60, 'End to End T.');
INSERT INTO technology(id, description)VALUES(61, 'UI Test');
INSERT INTO technology(id, description)VALUES(102360, 'HotJar');
INSERT INTO technology(id, description)VALUES(102440, 'Figma');
INSERT INTO technology(id, description)VALUES(102441, 'Design Thinking');
INSERT INTO technology(id, description)VALUES(102442, 'Miro');
INSERT INTO technology(id, description)VALUES(102443, 'Google Analytics');
INSERT INTO technology(id, description)VALUES(102444, 'Adobe Xd');
INSERT INTO technology(id, description)VALUES(102445, 'Sketch');
INSERT INTO technology(id, description)VALUES(102446, 'Zeplin');
INSERT INTO technology(id, description)VALUES(102447, 'InvisionApp');
INSERT INTO technology(id, description)VALUES(102448, 'Design Sprint');
INSERT INTO technology(id, description)VALUES(102449, 'Lean UX');
INSERT INTO technology(id, description)VALUES(102450, 'Adobe CC Suite');
INSERT INTO technology(id, description)VALUES(109025, 'Salesforce');
INSERT INTO technology(id, description)VALUES(109026, 'Apex');
INSERT INTO technology(id, description)VALUES(109027, 'SOQL');
INSERT INTO technology(id, description)VALUES(109028, 'SOSL');
INSERT INTO technology(id, description)VALUES(109029, 'Copado');
INSERT INTO technology(id, description)VALUES(109031, 'Aura');
INSERT INTO technology(id, description)VALUES(109033, 'LWC');
INSERT INTO technology(id, description)VALUES(109037, 'Provar');
INSERT INTO technology(id, description)VALUES(121122, 'SQL');
INSERT INTO technology(id, description)VALUES(121123, 'Mobile Testing');
INSERT INTO technology(id, description)VALUES(1645875, 'Other');
