INSERT INTO industry(id, description)VALUES(205, 'Financial Services');
INSERT INTO industry(id, description)VALUES(206, 'Media & Entertainment');
INSERT INTO industry(id, description)VALUES(207, 'Human Capital');
INSERT INTO industry(id, description)VALUES(208, 'Retail');
INSERT INTO industry(id, description)VALUES(85234, 'Aerospace');
INSERT INTO industry(id, description)VALUES(85235, 'Automotive');
INSERT INTO industry(id, description)VALUES(85236, 'Chemical');
INSERT INTO industry(id, description)VALUES(85237, 'Computer');
INSERT INTO industry(id, description)VALUES(85238, 'Construction');
INSERT INTO industry(id, description)VALUES(85239, 'Defense');
INSERT INTO industry(id, description)VALUES(85240, 'Education');
INSERT INTO industry(id, description)VALUES(85241, 'Electrical power');
INSERT INTO industry(id, description)VALUES(85242, 'Electronics');
INSERT INTO industry(id, description)VALUES(85243, 'Energy');
INSERT INTO industry(id, description)VALUES(85245, 'Food');
INSERT INTO industry(id, description)VALUES(85246, 'Health care');
INSERT INTO industry(id, description)VALUES(85247, 'Hospitality');
INSERT INTO industry(id, description)VALUES(85248, 'Human Resources');
INSERT INTO industry(id, description)VALUES(85249, 'Industrial robot');
INSERT INTO industry(id, description)VALUES(85250, 'Information');
INSERT INTO industry(id, description)VALUES(85251, 'Insurance');
INSERT INTO industry(id, description)VALUES(85252, 'Internet');
INSERT INTO industry(id, description)VALUES(85253, 'Low to medium tech');
INSERT INTO industry(id, description)VALUES(85254, 'Petroleum');
INSERT INTO industry(id, description)VALUES(85255, 'Mining');
INSERT INTO industry(id, description)VALUES(85256, 'Pharmaceutical');
INSERT INTO industry(id, description)VALUES(85257, 'Real estate');
INSERT INTO industry(id, description)VALUES(85258, 'Semiconductor');
INSERT INTO industry(id, description)VALUES(85259, 'Shipbuilding');
INSERT INTO industry(id, description)VALUES(85260, 'Software');
INSERT INTO industry(id, description)VALUES(85261, 'Sport');
INSERT INTO industry(id, description)VALUES(85262, 'Steel');
INSERT INTO industry(id, description)VALUES(85263, 'Telecommunications');
INSERT INTO industry(id, description)VALUES(85264, 'Textile');
INSERT INTO industry(id, description)VALUES(85265, 'Transport');
INSERT INTO industry(id, description)VALUES(85266, 'Water');